apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aiagent-cert
spec:
  secretName: {{ .Values.ingress.tlsSecretName }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .Values.ingress.hostname }}
  dnsNames:
  - {{ .Values.ingress.hostname }}

