{{- if and .Values.redis.enabled .Values.redis.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: aiagent-redis-secret
type: Opaque
data:
  redis-password: {{ randAlphaNum 32 | b64enc }}
{{- end }}

