apiVersion: v1
kind: Service
metadata:
  name: aiagent
spec:
  type: {{ .Values.service.type }}
  selector:
    app: aiagent
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 8000

